# Generated by Django 5.1.7 on 2025-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.AddField(
            model_name='faculty',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Diploma', 'Diploma')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('MCA', 'MCA'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=20),
        ),
    ]
